### PR TITLE
Add calibration parts for additive simulations

### PR DESCRIPTION
**Pull request by pkrull-ansys**

### CODE REVIEW

**Review by jorgepiloto — CHANGES_REQUESTED** [review]
Thanks for opening this, @pkrull-ansys. I would only suggest to use [snake_case](https://en.wikipedia.org/wiki/Snake_case) since the rest of files in the PyAdditive examples are using this naming convention.

**Review by RobPasMue — CHANGES_REQUESTED** [review]
I agree with @jorgepiloto. Plus, if these are "data" files I recommend to name the folder as such.

**Comment by pkrull-ansys** [comment]
@jorgepiloto @RobPasMue I've renamed the files and folder. Please re-review.

**Review by RobPasMue — APPROVED** [review]

**Comment by pkrull-ansys** [comment]
@jorgepiloto Can I get your approval on this?

**Review by jorgepiloto — APPROVED** [review]
Approved, @pkrull-ansys. Merging this 🚀

**Pull request merged**
