### PR TITLE
Added an example project file structure to extract case file from

### PR DESCRIPTION
**Pull request by prmukherj**

### CODE REVIEW

**Review by RobPasMue — COMMENTED** [review]
Are the `project.lock`and `*.flprj` files necessary? Other examples don't have those files, as far as I am aware of.

**Comment by mkundu1** [comment]
@prmukherj The .lock file is not required. There is also an .flprz format which we need to support.

**Comment by prmukherj** [comment]
@RobPasMue , Actually we need the folder structure as provided. So the contents of the file are not important, however for maintaining the structure and checking if it is a fluent project file, we are checking the existence of the *.flprj. So, I'll remove the .lock file and keep the *.flprj, ok?

**Comment by prmukherj** [comment]
@mkundu1 , ok Thank you. I'll do that as well.

**Comment by prmukherj** [comment]
@RobPasMue , @mkundu1 , I think this should be fine, right?

**Review by RobPasMue — APPROVED** [review]
LGTM!

**Pull request merged**
